import xml.etree.ElementTree as ET, re, csv, json, datetime, html
SC = '/tmp/claude-0/-home-claude/caa41b06-a6fa-52e1-921e-71f753b36efe/scratchpad/'
CT = '/root/.claude/uploads/caa41b06-a6fa-52e1-921e-71f753b36efe/911cc544-1789218157598_P4G.CT'
t = open(CT, 'rb').read().decode('utf-8')
root = ET.fromstring(t)
blocks = re.findall(r'<DropDownList ReadOnly="1" DescriptionOnly="1" DisplayValueAsItem="1">(.*?)</DropDownList>', t, flags=re.S)
SKILL_DD = [b for b in blocks if b.startswith('0000:N/A')][0]
PERSONA_DD = [b for b in blocks if b.startswith('0:N/A')][0]

def cstr(s):
    s = html.unescape(s)
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

# ---- skills: the table's vanilla list + the ailment skills it lacks (same numbering as the game, IDs from SKILL.TBL) ----
skills = {}
for l in SKILL_DD.split('\r\n'):
    if ':' not in l: continue
    i, rest = l.split(':', 1)
    name = rest.split(' (')[0].strip()
    desc = rest[len(name):].strip().replace('\t', ' ')
    if desc.startswith('('): desc = desc[1:]
    if desc.endswith(')'): desc = desc[:-1]
    desc = desc.replace(') (', ' - ').strip()
    if name.startswith('Endure Survive'): name, desc = 'Endure', 'Survive KO with 1 HP once per battle'
    skills[int(i, 16)] = (name, desc)
extra = {91: ('Poison Mist', 'Chance of Poison to all foes'), 84: ('Tentarafoo', 'Chance of Panic to all foes'), 98: ('Foolish Whisper', 'Chance of Silence to all foes'),
         95: ('Old One', 'Chance of Enervation to all foes'), 244: ('Trafuri', 'Escape from battle'), 86: ('Evil Smile', 'Chance of Fear to all foes'),
         92: ('Soul Break', 'Chance of Exhaustion to all foes'), 97: ('Makajam', 'Chance of Silence to one foe'), 83: ('Pulinpa', 'Chance of Panic to one foe'),
         90: ('Poisma', 'Chance of Poison to one foe'), 94: ('Enervation', 'Chance of Enervation to one foe'), 89: ('Valiant Dance', 'Chance of Rage to all foes'),
         93: ('Anima Freeze', 'Chance of Exhaustion to one foe'), 85: ('Evil Touch', 'Chance of Fear to one foe'), 88: ('Balzac', 'Chance of Rage to one foe')}
for k, v in extra.items(): skills.setdefault(k, v)
skill_rows = sorted(skills.items())

# ---- personas ----
personas = []
for l in PERSONA_DD.split('\r\n'):
    if ':' in l:
        i, n = l.split(':', 1); personas.append((int(i), n.strip()))
personas.sort()

# ---- items: categories from the table ----
def kids(ce): return ce.findall('CheatEntries/CheatEntry')
top = {ce.findtext('Description').strip('"'): ce for ce in root.findall('CheatEntries/CheatEntry')}
cats = []
def leaf_items(ce):
    out = []
    for c in kids(ce):
        if c.findtext('VariableType') == 'Byte' and c.findtext('Address'):
            a = c.findtext('Address').strip()
            if a.startswith('P4G.exe+'): addr = 0x140000000 + int(a[8:], 16)
            else: addr = int(a, 16)
            out.append((c.findtext('Description').strip('"').strip(), addr))
    return out
def collect(ce, prefix):
    for c in kids(ce):
        d = c.findtext('Description').strip('"').strip()
        if c.findtext('VariableType') == 'Auto Assembler Script' or d.startswith('----'): continue
        if kids(c):
            items = leaf_items(c)
            name = re.sub(r'\s*\(\d+\)\s*$', '', d.lstrip('~'))
            name = name.replace(' (Sorted By Power)', '').replace(' (Sorted By Def)', '').replace('Costume List', 'Costumes')
            for suf in (' Weapons', ' Armor', ' Accessories', ' Materials'):
                if prefix and name.endswith(suf): name = name[:-len(suf)]
            if items: cats.append((prefix + name, items))
            collect(c, prefix + name + ' / ' if not items else prefix)
collect(top['~Consumables (1451BD0A0) '], '')
collect(top['~Inventory'], '')
print('categories', len(cats), 'items', sum(len(i) for _, i in cats))

# ---- compendium rows (vanilla): generated by make_ct3.py in vanilla mode ----
vt = open('/mnt/user-data/outputs/P4G Vanilla v3.CT', 'rb').read().decode('utf-8')
m = re.search(r'local rows = \{\r\n(.*?)\r\n\}', vt, flags=re.S)
comp = [[int(x) for x in l.strip().strip('{},').split(',')] for l in m.group(1).split('\r\n')]
print('compendium rows', len(comp))

# ---- social links, romance, social stats, calendar ----
CMM = [(1, 'Investigation Team', 'Fool'), (2, 'Nanako Dojima', 'Justice'), (3, 'Rise Kujikawa', 'Lovers'), (4, 'Rise Kujikawa (variant)', 'Lovers'),
       (5, 'Yukiko Amagi', 'Priestess'), (6, 'Yukiko Amagi (variant)', 'Priestess'), (7, 'Yosuke Hanamura', 'Magician'), (8, 'Ryotaro Dojima', 'Hierophant'),
       (9, 'Sayoko Uehara (Nurse)', 'Devil'), (10, 'Kanji Tatsumi', 'Emperor'), (11, 'Chie Satonaka', 'Chariot'), (12, 'Chie Satonaka (variant)', 'Chariot'),
       (13, 'Fox', 'Hermit'), (14, 'Naoto Shirogane', 'Fortune'), (15, 'Naoto Shirogane (variant)', 'Fortune'), (16, 'Fellow Athletes - Kou', 'Strength'),
       (17, 'Fellow Athletes - Daisuke', 'Strength'), (18, "Naoki Konishi", 'Hanged Man'), (19, 'Hisano Kuroda', 'Death'), (20, 'Margaret', 'Empress'),
       (21, 'Ai Ebihara', 'Moon'), (22, 'Ai Ebihara (romance)', 'Moon'), (23, 'Shu Nakajima', 'Tower'), (24, 'Teddie', 'Star'), (25, 'Yumi Ozawa', 'Sun'),
       (26, 'Yumi Ozawa (variant)', 'Sun'), (27, 'Ayane Matsunaga', 'Sun'), (28, 'Ayane Matsunaga (variant)', 'Sun'), (29, 'Eri Minami', 'Temperance'),
       (30, 'Seekers of Truth', 'Judgement'), (31, 'Tohru Adachi', 'Jester'), (32, 'Tohru Adachi', 'Hunger'), (33, 'Marie', 'Aeon'), (34, 'Marie (variant)', 'Aeon')]
ROMANCE = [(2383, 'Marie'), (2384, 'Chie'), (2385, 'Yukiko'), (2386, 'Rise'), (2388, 'Ai Ebihara'), (2389, 'Yumi Ozawa'), (2390, 'Ayane Matsunaga'), (2621, 'Naoto')]
SOCIAL = [('Courage', ('Average', 'Reliable', 'Brave', 'Daring', 'Heroic'), (16, 24, 40, 60)),
          ('Knowledge', ('Aware', 'Informed', 'Expert', 'Professor', 'Sage'), (30, 50, 70, 90)),
          ('Diligence', ('Callow', 'Persistent', 'Strong', 'Thorough', 'Rock Solid'), (16, 24, 40, 50)),
          ('Understanding', ('Basic', 'Kindly', 'Generous', 'Motherly', 'Saintly'), (16, 24, 40, 60)),
          ('Expression', ('Rough', 'Eloquent', 'Persuasive', 'Touching', 'Enthralling'), (13, 20, 20, 32))]
d0 = datetime.date(2011, 4, 1)
dates = [(d0 + datetime.timedelta(days=i)).strftime('%m/%d %a') for i in range(366)]

out = []
out.append('// generated by gen_data.py from the vanilla P4G cheat table - do not edit by hand')
out.append('#pragma once\n#include <cstdint>\n#include <cstddef>')
out.append('struct SkillDef { uint16_t id; const char* name; const char* desc; };')
out.append('static const SkillDef SKILLS[] = {')
for i, (n, dsc) in skill_rows: out.append(f'  {{{i}, {cstr(n)}, {cstr(dsc)}}},')
out.append('};\nstatic const size_t SKILL_COUNT = sizeof(SKILLS)/sizeof(SKILLS[0]);')
out.append('struct PersonaDef { uint16_t id; const char* name; };')
out.append('static const PersonaDef PERSONAS[] = {')
for i, n in personas: out.append(f'  {{{i}, {cstr(n)}}},')
out.append('};\nstatic const size_t PERSONA_COUNT = sizeof(PERSONAS)/sizeof(PERSONAS[0]);')
out.append('struct ItemDef { const char* name; uint64_t addr; };')
out.append('struct ItemCat { const char* name; const ItemDef* items; size_t count; };')
for ci, (cname, items) in enumerate(cats):
    out.append(f'static const ItemDef ITEMS_{ci}[] = {{')
    for n, a in items: out.append(f'  {{{cstr(n)}, 0x{a:X}ULL}},')
    out.append('};')
out.append('static const ItemCat ITEM_CATS[] = {')
for ci, (cname, items) in enumerate(cats): out.append(f'  {{{cstr(cname)}, ITEMS_{ci}, sizeof(ITEMS_{ci})/sizeof(ITEMS_{ci}[0])}},')
out.append('};\nstatic const size_t ITEM_CAT_COUNT = sizeof(ITEM_CATS)/sizeof(ITEM_CATS[0]);')
out.append('struct CompRow { uint16_t id, level; uint32_t exp; uint8_t st, ma, en, ag, lu; uint16_t skills[8]; };')
out.append('static const CompRow COMP_ROWS[] = {')
for r in comp: out.append(f'  {{{r[0]}, {r[1]}, {r[2]}u, {r[3]}, {r[4]}, {r[5]}, {r[6]}, {r[7]}, {{{",".join(str(x) for x in r[8:16])}}}}},')
out.append('};\nstatic const size_t COMP_ROW_COUNT = sizeof(COMP_ROWS)/sizeof(COMP_ROWS[0]);')
out.append('struct CmmDef { uint16_t id; const char* name; const char* arcana; };')
out.append('static const CmmDef CMM[] = {')
for i, n, a in CMM: out.append(f'  {{{i}, {cstr(n)}, {cstr(a)}}},')
out.append('};\nstatic const size_t CMM_COUNT = sizeof(CMM)/sizeof(CMM[0]);')
out.append('struct RomanceDef { uint16_t bit; const char* name; };')
out.append('static const RomanceDef ROMANCE[] = {')
for b, n in ROMANCE: out.append(f'  {{{b}, {cstr(n)}}},')
out.append('};\nstatic const size_t ROMANCE_COUNT = sizeof(ROMANCE)/sizeof(ROMANCE[0]);')
out.append('struct SocialDef { const char* name; const char* ranks[5]; uint16_t inc[4]; };')
out.append('static const SocialDef SOCIAL[5] = {')
for n, ranks, inc in SOCIAL: out.append(f'  {{{cstr(n)}, {{{",".join(cstr(r) for r in ranks)}}}, {{{",".join(str(x) for x in inc)}}}}},')
out.append('};')
out.append('static const char* const DATES[366] = {')
for i in range(0, 366, 6): out.append('  ' + ', '.join(cstr(x) for x in dates[i:i+6]) + ',')
out.append('};')
out.append('static const char* const TOD_NAMES[6] = {"Early Morning", "Morning", "Lunchtime", "Afternoon", "After School", "Evening"};')
out.append('static const char* const AFF_NAMES[16] = {"Physical","Fire","Ice","Elec","Wind","Almighty","Light","Dark","Panic","Poison","Fear","Rage","Dizzy","Exhaustion","Enervation","Silence"};')
open(SC + 'trainer/src/data.h', 'w').write('\n'.join(out) + '\n')
print('skills', len(skill_rows), 'personas', len(personas), 'written data.h', len('\n'.join(out)))
